PROJECT_ROOT = r"C:/kurssit/gradu/koodi/numba_mcerd"
DATA_ROOT = rf"{PROJECT_ROOT}/data"
CONSTANTS_ROOT = rf"{DATA_ROOT}/constants"
GSTO_ROOT = rf"{DATA_ROOT}/gsto"
PICKLE_ROOT = rf"{DATA_ROOT}/pickled"
