"""Symbols from symbols.h"""

SYM_DEG = "deg"
SYM_US = "us"
SYM_UM = "um"
SYM_A = "A"
SYM_U = "U"
SYM_EV_A = "eV/A"
SYM_KEV_UM = "KeV/um"
SYM_KEV_UG_CM2 = "keV/(ug/cm2)"
SYM_EVCM2_1E15ATOMS = "eV/(1e15 atoms/cm2)"
SYM_MEV_MG_CM2 = "MeV/(mg/cm2)"
SYM_EV_UG_CM2 = "eV/(ug/cm2)"
SYM_G_CM3 = "g/cm"
SYM_KG_M3 = "kg/m3"
SYM_2 = "2"
SYM_3 = "3"
SYM_PM = "+-"
SYM_1_M3 = "1/m3"
